services:
  api:
    build: ../services/api
    ports: ["8050:8050"]
    env_file: ["../services/api/.env"]
    depends_on: ["ai"]
  ai:
    build: ../services/ai
    ports: ["8000:8000"]
    env_file: ["../services/ai/.env"]
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rewindday
    ports: ["5432:5432"]
    volumes: ["db_data:/var/lib/postgresql/data"]
volumes: { db_data: {} }
